<!-- <div>
  <iframe src="https://weevers.mythreekit.com" width="100%" height="600" scrolling="yes" style=" margin-top:-4px; margin-left:-4px; border:none;"></iframe>
</div> -->


<head>
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.2/semantic.min.css">
  <link href="web/css/main.css" rel="stylesheet">
</head>
<div class="" data-role="clara-player" id="clara-player" style="height:500px">
  <div id="root">
</div>
<script type="text/x-magento-init">
  {
    "[data-role=clara-player]": {
      "js/clara-player": {
      }
    }
  }
</script>
