<?php
/**
 * Copyright © Exocortex, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block Magento\Bundle\Block\Catalog\Product\View\Type\Bundle */ ?>
<?php
$product = $block->getProduct();
?>
<?php if ($product->isSaleable() && $block->hasOptions()):?>
  <li><iframe src="https://weevers.mythreekit.com" width="600" height="400" scrolling="yes" style=" margin-top:-4px; margin-left:-4px; border:none;"></iframe></li>
<?php endif;?>
